(function(a,b){function c(b,e){var f=b.nodeName.toLowerCase();if("area"===f){var f=b.parentNode,c=f.name;if(!b.href||!c||"map"!==f.nodeName.toLowerCase())return!1;f=a("img[usemap=#"+c+"]")[0];return!!f&&d(f)}return(/input|select|textarea|button|object/.test(f)?!b.disabled:"a"==f?b.href||e:e)&&d(b)}function d(b){return!a(b).parents().andSelf().filter(function(){return"hidden"===a.curCSS(this,"visibility")||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};a.ui.version||(a.extend(a.ui,{version:"1.8.16",
keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}}),a.fn.extend({propAttr:a.fn.prop||a.fn.attr,_focus:a.fn.focus,focus:function(b,e){return"number"===typeof b?this.each(function(){var f=
this;setTimeout(function(){a(f).focus();e&&e.call(f)},b)}):this._focus.apply(this,arguments)},scrollParent:function(){var b;b=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,
"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!b.length?a(document):b},zIndex:function(c){if(c!==b)return this.css("zIndex",c);if(this.length)for(var c=a(this[0]),e;c.length&&c[0]!==document;){e=c.css("position");if("absolute"===e||"relative"===e||"fixed"===e)if(e=parseInt(c.css("zIndex"),10),!isNaN(e)&&0!==e)return e;c=c.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":
"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}}),a.each(["Width","Height"],function(c,e){function f(e,f,b,c){a.each(d,function(){f-=parseFloat(a.curCSS(e,"padding"+this,!0))||0;b&&(f-=parseFloat(a.curCSS(e,"border"+this+"Width",!0))||0);c&&(f-=parseFloat(a.curCSS(e,"margin"+this,!0))||0)});return f}var d="Width"===e?["Left","Right"]:["Top","Bottom"],j=e.toLowerCase(),k={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,
outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+e]=function(c){return c===b?k["inner"+e].call(this):this.each(function(){a(this).css(j,f(this,c)+"px")})};a.fn["outer"+e]=function(b,c){return"number"!==typeof b?k["outer"+e].call(this,b):this.each(function(){a(this).css(j,f(this,b,!0,c)+"px")})}}),a.extend(a.expr[":"],{data:function(b,e,f){return!!a.data(b,f[3])},focusable:function(b){return c(b,!isNaN(a.attr(b,"tabindex")))},tabbable:function(b){var e=a.attr(b,"tabindex"),f=isNaN(e);
return(f||0<=e)&&c(b,!f)}}),a(function(){var b=document.body,e=b.appendChild(e=document.createElement("div"));a.extend(e.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=100===e.offsetHeight;a.support.selectstart="onselectstart"in e;b.removeChild(e).style.display="none"}),a.extend(a.ui,{plugin:{add:function(b,e,f){var b=a.ui[b].prototype,c;for(c in f)b.plugins[c]=b.plugins[c]||[],b.plugins[c].push([e,f[c]])},call:function(a,e,f){if((e=a.plugins[e])&&a.element[0].parentNode)for(var b=
0;b<e.length;b++)a.options[e[b][0]]&&e[b][1].apply(a.element,f)}},contains:function(a,e){return document.compareDocumentPosition?a.compareDocumentPosition(e)&16:a!==e&&a.contains(e)},hasScroll:function(b,e){if("hidden"===a(b).css("overflow"))return!1;var f=e&&"left"===e?"scrollLeft":"scrollTop",c=!1;if(0<b[f])return!0;b[f]=1;c=0<b[f];b[f]=0;return c},isOverAxis:function(a,e,b){return a>e&&a<e+b},isOver:function(b,e,f,c,d,k){return a.ui.isOverAxis(b,f,d)&&a.ui.isOverAxis(e,c,k)}}))})(jQuery);
(function(a,b){if(a.cleanData){var c=a.cleanData;a.cleanData=function(b){for(var e=0,f;null!=(f=b[e]);e++)try{a(f).triggerHandler("remove")}catch(d){}c(b)}}else{var d=a.fn.remove;a.fn.remove=function(b,e){return this.each(function(){e||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){try{a(this).triggerHandler("remove")}catch(e){}});return d.call(a(this),b,e)})}}a.widget=function(b,e,f){var c=b.split(".")[0],d,b=b.split(".")[1];d=c+"-"+b;if(!f)f=e,e=a.Widget;a.expr[":"][d]=
function(e){return!!a.data(e,b)};a[c]=a[c]||{};a[c][b]=function(a,e){arguments.length&&this._createWidget(a,e)};e=new e;e.options=a.extend(!0,{},e.options);a[c][b].prototype=a.extend(!0,e,{namespace:c,widgetName:b,widgetEventPrefix:a[c][b].prototype.widgetEventPrefix||b,widgetBaseClass:d},f);a.widget.bridge(b,a[c][b])};a.widget.bridge=function(c,e){a.fn[c]=function(f){var d="string"===typeof f,j=Array.prototype.slice.call(arguments,1),k=this,f=!d&&j.length?a.extend.apply(null,[!0,f].concat(j)):f;
if(d&&"_"===f.charAt(0))return k;d?this.each(function(){var e=a.data(this,c),d=e&&a.isFunction(e[f])?e[f].apply(e,j):e;if(d!==e&&d!==b)return k=d,!1}):this.each(function(){var b=a.data(this,c);b?b.option(f||{})._init():a.data(this,c,new e(f,this))});return k}};a.Widget=function(a,e){arguments.length&&this._createWidget(a,e)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:!1},_createWidget:function(b,e){a.data(e,this.widgetName,this);this.element=a(e);this.options=a.extend(!0,
{},this.options,this._getCreateOptions(),b);var f=this;this.element.bind("remove."+this.widgetName,function(){f.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+
"-disabled ui-state-disabled")},widget:function(){return this.element},option:function(c,e){var f=c;if(0===arguments.length)return a.extend({},this.options);if("string"===typeof c){if(e===b)return this.options[c];f={};f[c]=e}this._setOptions(f);return this},_setOptions:function(b){var e=this;a.each(b,function(a,b){e._setOption(a,b)});return this},_setOption:function(a,e){this.options[a]=e;"disabled"===a&&this.widget()[e?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",
e);return this},enable:function(){return this._setOption("disabled",!1)},disable:function(){return this._setOption("disabled",!0)},_trigger:function(b,e,f){var c=this.options[b],e=a.Event(e);e.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();f=f||{};if(e.originalEvent)for(var b=a.event.props.length,d;b;)d=a.event.props[--b],e[d]=e.originalEvent[d];this.element.trigger(e,f);return!(a.isFunction(c)&&!1===c.call(this.element[0],e,f)||e.isDefaultPrevented())}}})(jQuery);
(function(a){var b=!1;a(document).mouseup(function(){b=!1});a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var b=this;this.element.bind("mousedown."+this.widgetName,function(a){return b._mouseDown(a)}).bind("click."+this.widgetName,function(d){if(!0===a.data(d.target,b.widgetName+".preventClickEvent"))return a.removeData(d.target,b.widgetName+".preventClickEvent"),d.stopImmediatePropagation(),!1});this.started=!1},_mouseDestroy:function(){this.element.unbind("."+
this.widgetName)},_mouseDown:function(c){if(!b){this._mouseStarted&&this._mouseUp(c);this._mouseDownEvent=c;var d=this,g=1==c.which,e="string"==typeof this.options.cancel&&c.target.nodeName?a(c.target).closest(this.options.cancel).length:!1;if(!g||e||!this._mouseCapture(c))return!0;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){d.mouseDelayMet=!0},this.options.delay);if(this._mouseDistanceMet(c)&&this._mouseDelayMet(c)&&(this._mouseStarted=
!1!==this._mouseStart(c),!this._mouseStarted))return c.preventDefault(),!0;!0===a.data(c.target,this.widgetName+".preventClickEvent")&&a.removeData(c.target,this.widgetName+".preventClickEvent");this._mouseMoveDelegate=function(a){return d._mouseMove(a)};this._mouseUpDelegate=function(a){return d._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);c.preventDefault();return b=!0}},_mouseMove:function(b){if(a.browser.msie&&
!(9<=document.documentMode)&&!b.button)return this._mouseUp(b);if(this._mouseStarted)return this._mouseDrag(b),b.preventDefault();if(this._mouseDistanceMet(b)&&this._mouseDelayMet(b))(this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,b))?this._mouseDrag(b):this._mouseUp(b);return!this._mouseStarted},_mouseUp:function(b){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted)this._mouseStarted=
!1,b.target==this._mouseDownEvent.target&&a.data(b.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(b);return!1},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}})})(jQuery);
(function(a){a.ui=a.ui||{};var b=/left|center|right/,c=/top|center|bottom/,d=a.fn.position,g=a.fn.offset;a.fn.position=function(e){if(!e||!e.of)return d.apply(this,arguments);var e=a.extend({},e),f=a(e.of),h=f[0],j=(e.collision||"flip").split(" "),g=e.offset?e.offset.split(" "):[0,0],i,l,m;9===h.nodeType?(i=f.width(),l=f.height(),m={top:0,left:0}):h.setTimeout?(i=f.width(),l=f.height(),m={top:f.scrollTop(),left:f.scrollLeft()}):h.preventDefault?(e.at="left top",i=l=0,m={top:e.of.pageY,left:e.of.pageX}):
(i=f.outerWidth(),l=f.outerHeight(),m=f.offset());a.each(["my","at"],function(){var a=(e[this]||"").split(" ");1===a.length&&(a=b.test(a[0])?a.concat(["center"]):c.test(a[0])?["center"].concat(a):["center","center"]);a[0]=b.test(a[0])?a[0]:"center";a[1]=c.test(a[1])?a[1]:"center";e[this]=a});1===j.length&&(j[1]=j[0]);g[0]=parseInt(g[0],10)||0;1===g.length&&(g[1]=g[0]);g[1]=parseInt(g[1],10)||0;"right"===e.at[0]?m.left+=i:"center"===e.at[0]&&(m.left+=i/2);"bottom"===e.at[1]?m.top+=l:"center"===e.at[1]&&
(m.top+=l/2);m.left+=g[0];m.top+=g[1];return this.each(function(){var b=a(this),f=b.outerWidth(),c=b.outerHeight(),d=parseInt(a.curCSS(this,"marginLeft",!0))||0,h=parseInt(a.curCSS(this,"marginTop",!0))||0,q=f+d+(parseInt(a.curCSS(this,"marginRight",!0))||0),u=c+h+(parseInt(a.curCSS(this,"marginBottom",!0))||0),n=a.extend({},m),v;"right"===e.my[0]?n.left-=f:"center"===e.my[0]&&(n.left-=f/2);"bottom"===e.my[1]?n.top-=c:"center"===e.my[1]&&(n.top-=c/2);n.left=Math.round(n.left);n.top=Math.round(n.top);
v={left:n.left-d,top:n.top-h};a.each(["left","top"],function(b,d){if(a.ui.position[j[b]])a.ui.position[j[b]][d](n,{targetWidth:i,targetHeight:l,elemWidth:f,elemHeight:c,collisionPosition:v,collisionWidth:q,collisionHeight:u,offset:g,my:e.my,at:e.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(n,{using:e.using}))})};a.ui.position={fit:{left:function(b,f){var c=a(window),c=f.collisionPosition.left+f.collisionWidth-c.width()-c.scrollLeft();b.left=0<c?b.left-c:Math.max(b.left-f.collisionPosition.left,
b.left)},top:function(b,f){var c=a(window),c=f.collisionPosition.top+f.collisionHeight-c.height()-c.scrollTop();b.top=0<c?b.top-c:Math.max(b.top-f.collisionPosition.top,b.top)}},flip:{left:function(b,f){if("center"!==f.at[0]){var c=a(window),c=f.collisionPosition.left+f.collisionWidth-c.width()-c.scrollLeft(),d="left"===f.my[0]?-f.elemWidth:"right"===f.my[0]?f.elemWidth:0,g="left"===f.at[0]?f.targetWidth:-f.targetWidth,i=-2*f.offset[0];b.left+=0>f.collisionPosition.left?d+g+i:0<c?d+g+i:0}},top:function(b,
f){if("center"!==f.at[1]){var c=a(window),c=f.collisionPosition.top+f.collisionHeight-c.height()-c.scrollTop(),d="top"===f.my[1]?-f.elemHeight:"bottom"===f.my[1]?f.elemHeight:0,g="top"===f.at[1]?f.targetHeight:-f.targetHeight,i=-2*f.offset[1];b.top+=0>f.collisionPosition.top?d+g+i:0<c?d+g+i:0}}}};if(!a.offset.setOffset)a.offset.setOffset=function(b,c){if(/static/.test(a.curCSS(b,"position")))b.style.position="relative";var d=a(b),g=d.offset(),k=parseInt(a.curCSS(b,"top",!0),10)||0,i=parseInt(a.curCSS(b,
"left",!0),10)||0,g={top:c.top-g.top+k,left:c.left-g.left+i};"using"in c?c.using.call(b,g):d.css(g)},a.fn.offset=function(b){var c=this[0];return!c||!c.ownerDocument?null:b?this.each(function(){a.offset.setOffset(this,b)}):g.call(this)}})(jQuery);
(function(a){a.widget("ui.draggable",a.ui.mouse,{widgetEventPrefix:"drag",options:{addClasses:!0,appendTo:"parent",axis:!1,connectToSortable:!1,containment:!1,cursor:"auto",cursorAt:!1,grid:!1,handle:!1,helper:"original",iframeFix:!1,opacity:!1,refreshPositions:!1,revert:!1,revertDuration:500,scope:"default",scroll:!0,scrollSensitivity:20,scrollSpeed:20,snap:!1,snapMode:"both",snapTolerance:20,stack:!1,zIndex:!1},_create:function(){if("original"==this.options.helper&&!/^(?:r|a|f)/.test(this.element.css("position")))this.element[0].style.position=
"relative";this.options.addClasses&&this.element.addClass("ui-draggable");this.options.disabled&&this.element.addClass("ui-draggable-disabled");this._mouseInit()},destroy:function(){if(this.element.data("draggable"))return this.element.removeData("draggable").unbind(".draggable").removeClass("ui-draggable ui-draggable-dragging ui-draggable-disabled"),this._mouseDestroy(),this},_mouseCapture:function(b){var c=this.options;if(this.helper||c.disabled||a(b.target).is(".ui-resizable-handle"))return!1;
this.handle=this._getHandle(b);if(!this.handle)return!1;c.iframeFix&&a(!0===c.iframeFix?"iframe":c.iframeFix).each(function(){a('<div class="ui-draggable-iframeFix" style="background: #fff;"></div>').css({width:this.offsetWidth+"px",height:this.offsetHeight+"px",position:"absolute",opacity:"0.001",zIndex:1E3}).css(a(this).offset()).appendTo("body")});return!0},_mouseStart:function(b){var c=this.options;this.helper=this._createHelper(b);this._cacheHelperProportions();if(a.ui.ddmanager)a.ui.ddmanager.current=
this;this._cacheMargins();this.cssPosition=this.helper.css("position");this.scrollParent=this.helper.scrollParent();this.offset=this.positionAbs=this.element.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};a.extend(this.offset,{click:{left:b.pageX-this.offset.left,top:b.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this.position=this._generatePosition(b);this.originalPageX=b.pageX;
this.originalPageY=b.pageY;c.cursorAt&&this._adjustOffsetFromHelper(c.cursorAt);c.containment&&this._setContainment();if(!1===this._trigger("start",b))return this._clear(),!1;this._cacheHelperProportions();a.ui.ddmanager&&!c.dropBehaviour&&a.ui.ddmanager.prepareOffsets(this,b);this.helper.addClass("ui-draggable-dragging");this._mouseDrag(b,!0);a.ui.ddmanager&&a.ui.ddmanager.dragStart(this,b);return!0},_mouseDrag:function(b,c){this.position=this._generatePosition(b);this.positionAbs=this._convertPositionTo("absolute");
if(!c){var d=this._uiHash();if(!1===this._trigger("drag",b,d))return this._mouseUp({}),!1;this.position=d.position}if(!this.options.axis||"y"!=this.options.axis)this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||"x"!=this.options.axis)this.helper[0].style.top=this.position.top+"px";a.ui.ddmanager&&a.ui.ddmanager.drag(this,b);return!1},_mouseStop:function(b){var c=!1;a.ui.ddmanager&&!this.options.dropBehaviour&&(c=a.ui.ddmanager.drop(this,b));if(this.dropped)c=this.dropped,this.dropped=
!1;if((!this.element[0]||!this.element[0].parentNode)&&"original"==this.options.helper)return!1;if("invalid"==this.options.revert&&!c||"valid"==this.options.revert&&c||!0===this.options.revert||a.isFunction(this.options.revert)&&this.options.revert.call(this.element,c)){var d=this;a(this.helper).animate(this.originalPosition,parseInt(this.options.revertDuration,10),function(){!1!==d._trigger("stop",b)&&d._clear()})}else!1!==this._trigger("stop",b)&&this._clear();return!1},_mouseUp:function(b){!0===
this.options.iframeFix&&a("div.ui-draggable-iframeFix").each(function(){this.parentNode.removeChild(this)});a.ui.ddmanager&&a.ui.ddmanager.dragStop(this,b);return a.ui.mouse.prototype._mouseUp.call(this,b)},cancel:function(){this.helper.is(".ui-draggable-dragging")?this._mouseUp({}):this._clear();return this},_getHandle:function(b){var c=!this.options.handle||!a(this.options.handle,this.element).length?!0:!1;a(this.options.handle,this.element).find("*").andSelf().each(function(){this==b.target&&(c=
!0)});return c},_createHelper:function(b){var c=this.options,b=a.isFunction(c.helper)?a(c.helper.apply(this.element[0],[b])):"clone"==c.helper?this.element.clone().removeAttr("id"):this.element;b.parents("body").length||b.appendTo("parent"==c.appendTo?this.element[0].parentNode:c.appendTo);b[0]!=this.element[0]&&!/(fixed|absolute)/.test(b.css("position"))&&b.css("position","absolute");return b},_adjustOffsetFromHelper:function(b){"string"==typeof b&&(b=b.split(" "));a.isArray(b)&&(b={left:+b[0],top:+b[1]||
0});if("left"in b)this.offset.click.left=b.left+this.margins.left;if("right"in b)this.offset.click.left=this.helperProportions.width-b.right+this.margins.left;if("top"in b)this.offset.click.top=b.top+this.margins.top;if("bottom"in b)this.offset.click.top=this.helperProportions.height-b.bottom+this.margins.top},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var b=this.offsetParent.offset();"absolute"==this.cssPosition&&this.scrollParent[0]!=document&&a.ui.contains(this.scrollParent[0],
this.offsetParent[0])&&(b.left+=this.scrollParent.scrollLeft(),b.top+=this.scrollParent.scrollTop());if(this.offsetParent[0]==document.body||this.offsetParent[0].tagName&&"html"==this.offsetParent[0].tagName.toLowerCase()&&a.browser.msie)b={top:0,left:0};return{top:b.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:b.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if("relative"==this.cssPosition){var a=this.element.position();return{top:a.top-
(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.element.css("marginLeft"),10)||0,top:parseInt(this.element.css("marginTop"),10)||0,right:parseInt(this.element.css("marginRight"),10)||0,bottom:parseInt(this.element.css("marginBottom"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),
height:this.helper.outerHeight()}},_setContainment:function(){var b=this.options;if("parent"==b.containment)b.containment=this.helper[0].parentNode;if("document"==b.containment||"window"==b.containment)this.containment=["document"==b.containment?0:a(window).scrollLeft()-this.offset.relative.left-this.offset.parent.left,"document"==b.containment?0:a(window).scrollTop()-this.offset.relative.top-this.offset.parent.top,("document"==b.containment?0:a(window).scrollLeft())+a("document"==b.containment?document:
window).width()-this.helperProportions.width-this.margins.left,("document"==b.containment?0:a(window).scrollTop())+(a("document"==b.containment?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(b.containment)&&b.containment.constructor!=Array){var b=a(b.containment),c=b[0];if(c){b.offset();var d="hidden"!=a(c).css("overflow");this.containment=[(parseInt(a(c).css("borderLeftWidth"),10)||0)+(parseInt(a(c).css("paddingLeft"),
10)||0),(parseInt(a(c).css("borderTopWidth"),10)||0)+(parseInt(a(c).css("paddingTop"),10)||0),(d?Math.max(c.scrollWidth,c.offsetWidth):c.offsetWidth)-(parseInt(a(c).css("borderLeftWidth"),10)||0)-(parseInt(a(c).css("paddingRight"),10)||0)-this.helperProportions.width-this.margins.left-this.margins.right,(d?Math.max(c.scrollHeight,c.offsetHeight):c.offsetHeight)-(parseInt(a(c).css("borderTopWidth"),10)||0)-(parseInt(a(c).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top-this.margins.bottom];
this.relative_container=b}}else if(b.containment.constructor==Array)this.containment=b.containment},_convertPositionTo:function(b,c){if(!c)c=this.position;var d="absolute"==b?1:-1,g="absolute"==this.cssPosition&&!(this.scrollParent[0]!=document&&a.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,e=/(html|body)/i.test(g[0].tagName);return{top:c.top+this.offset.relative.top*d+this.offset.parent.top*d-(a.browser.safari&&526>a.browser.version&&"fixed"==this.cssPosition?
0:("fixed"==this.cssPosition?-this.scrollParent.scrollTop():e?0:g.scrollTop())*d),left:c.left+this.offset.relative.left*d+this.offset.parent.left*d-(a.browser.safari&&526>a.browser.version&&"fixed"==this.cssPosition?0:("fixed"==this.cssPosition?-this.scrollParent.scrollLeft():e?0:g.scrollLeft())*d)}},_generatePosition:function(b){var c=this.options,d="absolute"==this.cssPosition&&!(this.scrollParent[0]!=document&&a.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,
g=/(html|body)/i.test(d[0].tagName),e=b.pageX,f=b.pageY;if(this.originalPosition){var h;if(this.containment)this.relative_container?(h=this.relative_container.offset(),h=[this.containment[0]+h.left,this.containment[1]+h.top,this.containment[2]+h.left,this.containment[3]+h.top]):h=this.containment,b.pageX-this.offset.click.left<h[0]&&(e=h[0]+this.offset.click.left),b.pageY-this.offset.click.top<h[1]&&(f=h[1]+this.offset.click.top),b.pageX-this.offset.click.left>h[2]&&(e=h[2]+this.offset.click.left),
b.pageY-this.offset.click.top>h[3]&&(f=h[3]+this.offset.click.top);c.grid&&(f=c.grid[1]?this.originalPageY+Math.round((f-this.originalPageY)/c.grid[1])*c.grid[1]:this.originalPageY,f=h?!(f-this.offset.click.top<h[1]||f-this.offset.click.top>h[3])?f:!(f-this.offset.click.top<h[1])?f-c.grid[1]:f+c.grid[1]:f,e=c.grid[0]?this.originalPageX+Math.round((e-this.originalPageX)/c.grid[0])*c.grid[0]:this.originalPageX,e=h?!(e-this.offset.click.left<h[0]||e-this.offset.click.left>h[2])?e:!(e-this.offset.click.left<
h[0])?e-c.grid[0]:e+c.grid[0]:e)}return{top:f-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(a.browser.safari&&526>a.browser.version&&"fixed"==this.cssPosition?0:"fixed"==this.cssPosition?-this.scrollParent.scrollTop():g?0:d.scrollTop()),left:e-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+(a.browser.safari&&526>a.browser.version&&"fixed"==this.cssPosition?0:"fixed"==this.cssPosition?-this.scrollParent.scrollLeft():g?0:d.scrollLeft())}},_clear:function(){this.helper.removeClass("ui-draggable-dragging");
this.helper[0]!=this.element[0]&&!this.cancelHelperRemoval&&this.helper.remove();this.helper=null;this.cancelHelperRemoval=!1},_trigger:function(b,c,d){d=d||this._uiHash();a.ui.plugin.call(this,b,[c,d]);if("drag"==b)this.positionAbs=this._convertPositionTo("absolute");return a.Widget.prototype._trigger.call(this,b,c,d)},plugins:{},_uiHash:function(){return{helper:this.helper,position:this.position,originalPosition:this.originalPosition,offset:this.positionAbs}}});a.extend(a.ui.draggable,{version:"1.8.16"});
a.ui.plugin.add("draggable","connectToSortable",{start:function(b,c){var d=a(this).data("draggable"),g=d.options,e=a.extend({},c,{item:d.element});d.sortables=[];a(g.connectToSortable).each(function(){var c=a.data(this,"sortable");c&&!c.options.disabled&&(d.sortables.push({instance:c,shouldRevert:c.options.revert}),c.refreshPositions(),c._trigger("activate",b,e))})},stop:function(b,c){var d=a(this).data("draggable"),g=a.extend({},c,{item:d.element});a.each(d.sortables,function(){if(this.instance.isOver){this.instance.isOver=
0;d.cancelHelperRemoval=!0;this.instance.cancelHelperRemoval=!1;if(this.shouldRevert)this.instance.options.revert=!0;this.instance._mouseStop(b);this.instance.options.helper=this.instance.options._helper;"original"==d.options.helper&&this.instance.currentItem.css({top:"auto",left:"auto"})}else this.instance.cancelHelperRemoval=!1,this.instance._trigger("deactivate",b,g)})},drag:function(b,c){var d=a(this).data("draggable"),g=this;a.each(d.sortables,function(){this.instance.positionAbs=d.positionAbs;
this.instance.helperProportions=d.helperProportions;this.instance.offset.click=d.offset.click;if(this.instance._intersectsWith(this.instance.containerCache)){if(!this.instance.isOver)this.instance.isOver=1,this.instance.currentItem=a(g).clone().removeAttr("id").appendTo(this.instance.element).data("sortable-item",!0),this.instance.options._helper=this.instance.options.helper,this.instance.options.helper=function(){return c.helper[0]},b.target=this.instance.currentItem[0],this.instance._mouseCapture(b,
!0),this.instance._mouseStart(b,!0,!0),this.instance.offset.click.top=d.offset.click.top,this.instance.offset.click.left=d.offset.click.left,this.instance.offset.parent.left-=d.offset.parent.left-this.instance.offset.parent.left,this.instance.offset.parent.top-=d.offset.parent.top-this.instance.offset.parent.top,d._trigger("toSortable",b),d.dropped=this.instance.element,d.currentItem=d.element,this.instance.fromOutside=d;this.instance.currentItem&&this.instance._mouseDrag(b)}else if(this.instance.isOver)this.instance.isOver=
0,this.instance.cancelHelperRemoval=!0,this.instance.options.revert=!1,this.instance._trigger("out",b,this.instance._uiHash(this.instance)),this.instance._mouseStop(b,!0),this.instance.options.helper=this.instance.options._helper,this.instance.currentItem.remove(),this.instance.placeholder&&this.instance.placeholder.remove(),d._trigger("fromSortable",b),d.dropped=!1})}});a.ui.plugin.add("draggable","cursor",{start:function(){var b=a("body"),c=a(this).data("draggable").options;if(b.css("cursor"))c._cursor=
b.css("cursor");b.css("cursor",c.cursor)},stop:function(){var b=a(this).data("draggable").options;b._cursor&&a("body").css("cursor",b._cursor)}});a.ui.plugin.add("draggable","opacity",{start:function(b,c){var d=a(c.helper),g=a(this).data("draggable").options;if(d.css("opacity"))g._opacity=d.css("opacity");d.css("opacity",g.opacity)},stop:function(b,c){var d=a(this).data("draggable").options;d._opacity&&a(c.helper).css("opacity",d._opacity)}});a.ui.plugin.add("draggable","scroll",{start:function(){var b=
a(this).data("draggable");if(b.scrollParent[0]!=document&&"HTML"!=b.scrollParent[0].tagName)b.overflowOffset=b.scrollParent.offset()},drag:function(b){var c=a(this).data("draggable"),d=c.options,g=!1;if(c.scrollParent[0]!=document&&"HTML"!=c.scrollParent[0].tagName){if(!d.axis||"x"!=d.axis)if(c.overflowOffset.top+c.scrollParent[0].offsetHeight-b.pageY<d.scrollSensitivity)c.scrollParent[0].scrollTop=g=c.scrollParent[0].scrollTop+d.scrollSpeed;else if(b.pageY-c.overflowOffset.top<d.scrollSensitivity)c.scrollParent[0].scrollTop=
g=c.scrollParent[0].scrollTop-d.scrollSpeed;if(!d.axis||"y"!=d.axis)if(c.overflowOffset.left+c.scrollParent[0].offsetWidth-b.pageX<d.scrollSensitivity)c.scrollParent[0].scrollLeft=g=c.scrollParent[0].scrollLeft+d.scrollSpeed;else if(b.pageX-c.overflowOffset.left<d.scrollSensitivity)c.scrollParent[0].scrollLeft=g=c.scrollParent[0].scrollLeft-d.scrollSpeed}else{if(!d.axis||"x"!=d.axis)b.pageY-a(document).scrollTop()<d.scrollSensitivity?g=a(document).scrollTop(a(document).scrollTop()-d.scrollSpeed):
a(window).height()-(b.pageY-a(document).scrollTop())<d.scrollSensitivity&&(g=a(document).scrollTop(a(document).scrollTop()+d.scrollSpeed));if(!d.axis||"y"!=d.axis)b.pageX-a(document).scrollLeft()<d.scrollSensitivity?g=a(document).scrollLeft(a(document).scrollLeft()-d.scrollSpeed):a(window).width()-(b.pageX-a(document).scrollLeft())<d.scrollSensitivity&&(g=a(document).scrollLeft(a(document).scrollLeft()+d.scrollSpeed))}!1!==g&&a.ui.ddmanager&&!d.dropBehaviour&&a.ui.ddmanager.prepareOffsets(c,b)}});
a.ui.plugin.add("draggable","snap",{start:function(){var b=a(this).data("draggable"),c=b.options;b.snapElements=[];a(c.snap.constructor!=String?c.snap.items||":data(draggable)":c.snap).each(function(){var c=a(this),g=c.offset();this!=b.element[0]&&b.snapElements.push({item:this,width:c.outerWidth(),height:c.outerHeight(),top:g.top,left:g.left})})},drag:function(b,c){for(var d=a(this).data("draggable"),g=d.options,e=g.snapTolerance,f=c.offset.left,h=f+d.helperProportions.width,j=c.offset.top,k=j+d.helperProportions.height,
i=d.snapElements.length-1;0<=i;i--){var l=d.snapElements[i].left,m=l+d.snapElements[i].width,o=d.snapElements[i].top,p=o+d.snapElements[i].height;if(l-e<f&&f<m+e&&o-e<j&&j<p+e||l-e<f&&f<m+e&&o-e<k&&k<p+e||l-e<h&&h<m+e&&o-e<j&&j<p+e||l-e<h&&h<m+e&&o-e<k&&k<p+e){if("inner"!=g.snapMode){var r=Math.abs(o-k)<=e,s=Math.abs(p-j)<=e,t=Math.abs(l-h)<=e,q=Math.abs(m-f)<=e;if(r)c.position.top=d._convertPositionTo("relative",{top:o-d.helperProportions.height,left:0}).top-d.margins.top;if(s)c.position.top=d._convertPositionTo("relative",
{top:p,left:0}).top-d.margins.top;if(t)c.position.left=d._convertPositionTo("relative",{top:0,left:l-d.helperProportions.width}).left-d.margins.left;if(q)c.position.left=d._convertPositionTo("relative",{top:0,left:m}).left-d.margins.left}var u=r||s||t||q;if("outer"!=g.snapMode){r=Math.abs(o-j)<=e;s=Math.abs(p-k)<=e;t=Math.abs(l-f)<=e;q=Math.abs(m-h)<=e;if(r)c.position.top=d._convertPositionTo("relative",{top:o,left:0}).top-d.margins.top;if(s)c.position.top=d._convertPositionTo("relative",{top:p-d.helperProportions.height,
left:0}).top-d.margins.top;if(t)c.position.left=d._convertPositionTo("relative",{top:0,left:l}).left-d.margins.left;if(q)c.position.left=d._convertPositionTo("relative",{top:0,left:m-d.helperProportions.width}).left-d.margins.left}!d.snapElements[i].snapping&&(r||s||t||q||u)&&d.options.snap.snap&&d.options.snap.snap.call(d.element,b,a.extend(d._uiHash(),{snapItem:d.snapElements[i].item}));d.snapElements[i].snapping=r||s||t||q||u}else d.snapElements[i].snapping&&d.options.snap.release&&d.options.snap.release.call(d.element,
b,a.extend(d._uiHash(),{snapItem:d.snapElements[i].item})),d.snapElements[i].snapping=!1}}});a.ui.plugin.add("draggable","stack",{start:function(){var b=a(this).data("draggable").options,b=a.makeArray(a(b.stack)).sort(function(b,c){return(parseInt(a(b).css("zIndex"),10)||0)-(parseInt(a(c).css("zIndex"),10)||0)});if(b.length){var c=parseInt(b[0].style.zIndex)||0;a(b).each(function(a){this.style.zIndex=c+a});this[0].style.zIndex=c+b.length}}});a.ui.plugin.add("draggable","zIndex",{start:function(b,
c){var d=a(c.helper),g=a(this).data("draggable").options;if(d.css("zIndex"))g._zIndex=d.css("zIndex");d.css("zIndex",g.zIndex)},stop:function(b,c){var d=a(this).data("draggable").options;d._zIndex&&a(c.helper).css("zIndex",d._zIndex)}})})(jQuery);
(function(a){a.widget("ui.droppable",{widgetEventPrefix:"drop",options:{accept:"*",activeClass:!1,addClasses:!0,greedy:!1,hoverClass:!1,scope:"default",tolerance:"intersect"},_create:function(){var b=this.options,c=b.accept;this.isover=0;this.isout=1;this.accept=a.isFunction(c)?c:function(a){return a.is(c)};this.proportions={width:this.element[0].offsetWidth,height:this.element[0].offsetHeight};a.ui.ddmanager.droppables[b.scope]=a.ui.ddmanager.droppables[b.scope]||[];a.ui.ddmanager.droppables[b.scope].push(this);
b.addClasses&&this.element.addClass("ui-droppable")},destroy:function(){for(var b=a.ui.ddmanager.droppables[this.options.scope],c=0;c<b.length;c++)b[c]==this&&b.splice(c,1);this.element.removeClass("ui-droppable ui-droppable-disabled").removeData("droppable").unbind(".droppable");return this},_setOption:function(b,c){if("accept"==b)this.accept=a.isFunction(c)?c:function(a){return a.is(c)};a.Widget.prototype._setOption.apply(this,arguments)},_activate:function(b){var c=a.ui.ddmanager.current;this.options.activeClass&&
this.element.addClass(this.options.activeClass);c&&this._trigger("activate",b,this.ui(c))},_deactivate:function(b){var c=a.ui.ddmanager.current;this.options.activeClass&&this.element.removeClass(this.options.activeClass);c&&this._trigger("deactivate",b,this.ui(c))},_over:function(b){var c=a.ui.ddmanager.current;if(c&&(c.currentItem||c.element)[0]!=this.element[0])if(this.accept.call(this.element[0],c.currentItem||c.element))this.options.hoverClass&&this.element.addClass(this.options.hoverClass),this._trigger("over",
b,this.ui(c))},_out:function(b){var c=a.ui.ddmanager.current;if(c&&(c.currentItem||c.element)[0]!=this.element[0])if(this.accept.call(this.element[0],c.currentItem||c.element))this.options.hoverClass&&this.element.removeClass(this.options.hoverClass),this._trigger("out",b,this.ui(c))},_drop:function(b,c){var d=c||a.ui.ddmanager.current;if(!d||(d.currentItem||d.element)[0]==this.element[0])return!1;var g=!1;this.element.find(":data(droppable)").not(".ui-draggable-dragging").each(function(){var b=a.data(this,
"droppable");if(b.options.greedy&&!b.options.disabled&&b.options.scope==d.options.scope&&b.accept.call(b.element[0],d.currentItem||d.element)&&a.ui.intersect(d,a.extend(b,{offset:b.element.offset()}),b.options.tolerance))return g=!0,!1});if(g)return!1;return this.accept.call(this.element[0],d.currentItem||d.element)?(this.options.activeClass&&this.element.removeClass(this.options.activeClass),this.options.hoverClass&&this.element.removeClass(this.options.hoverClass),this._trigger("drop",b,this.ui(d)),
this.element):!1},ui:function(a){return{draggable:a.currentItem||a.element,helper:a.helper,position:a.position,offset:a.positionAbs}}});a.extend(a.ui.droppable,{version:"1.8.16"});a.ui.intersect=function(b,c,d){if(!c.offset)return!1;var g=(b.positionAbs||b.position.absolute).left,e=g+b.helperProportions.width,f=(b.positionAbs||b.position.absolute).top,h=f+b.helperProportions.height,j=c.offset.left,k=j+c.proportions.width,i=c.offset.top,l=i+c.proportions.height;switch(d){case "fit":return j<=g&&e<=
k&&i<=f&&h<=l;case "intersect":return j<g+b.helperProportions.width/2&&e-b.helperProportions.width/2<k&&i<f+b.helperProportions.height/2&&h-b.helperProportions.height/2<l;case "pointer":return a.ui.isOver((b.positionAbs||b.position.absolute).top+(b.clickOffset||b.offset.click).top,(b.positionAbs||b.position.absolute).left+(b.clickOffset||b.offset.click).left,i,j,c.proportions.height,c.proportions.width);case "touch":return(f>=i&&f<=l||h>=i&&h<=l||f<i&&h>l)&&(g>=j&&g<=k||e>=j&&e<=k||g<j&&e>k);default:return!1}};
a.ui.ddmanager={current:null,droppables:{"default":[]},prepareOffsets:function(b,c){var d=a.ui.ddmanager.droppables[b.options.scope]||[],g=c?c.type:null,e=(b.currentItem||b.element).find(":data(droppable)").andSelf(),f=0;a:for(;f<d.length;f++)if(!(d[f].options.disabled||b&&!d[f].accept.call(d[f].element[0],b.currentItem||b.element))){for(var h=0;h<e.length;h++)if(e[h]==d[f].element[0]){d[f].proportions.height=0;continue a}d[f].visible="none"!=d[f].element.css("display");if(d[f].visible)"mousedown"==
g&&d[f]._activate.call(d[f],c),d[f].offset=d[f].element.offset(),d[f].proportions={width:d[f].element[0].offsetWidth,height:d[f].element[0].offsetHeight}}},drop:function(b,c){var d=!1;a.each(a.ui.ddmanager.droppables[b.options.scope]||[],function(){if(this.options&&(!this.options.disabled&&this.visible&&a.ui.intersect(b,this,this.options.tolerance)&&(d=d||this._drop.call(this,c)),!this.options.disabled&&this.visible&&this.accept.call(this.element[0],b.currentItem||b.element)))this.isout=1,this.isover=
0,this._deactivate.call(this,c)});return d},dragStart:function(b,c){b.element.parents(":not(body,html)").bind("scroll.droppable",function(){b.options.refreshPositions||a.ui.ddmanager.prepareOffsets(b,c)})},drag:function(b,c){b.options.refreshPositions&&a.ui.ddmanager.prepareOffsets(b,c);a.each(a.ui.ddmanager.droppables[b.options.scope]||[],function(){if(!this.options.disabled&&!this.greedyChild&&this.visible){var d=a.ui.intersect(b,this,this.options.tolerance);if(d=!d&&1==this.isover?"isout":d&&0==
this.isover?"isover":null){var g;if(this.options.greedy){var e=this.element.parents(":data(droppable):eq(0)");if(e.length)g=a.data(e[0],"droppable"),g.greedyChild="isover"==d?1:0}if(g&&"isover"==d)g.isover=0,g.isout=1,g._out.call(g,c);this[d]=1;this["isout"==d?"isover":"isout"]=0;this["isover"==d?"_over":"_out"].call(this,c);if(g&&"isout"==d)g.isout=0,g.isover=1,g._over.call(g,c)}}})},dragStop:function(b,c){b.element.parents(":not(body,html)").unbind("scroll.droppable");b.options.refreshPositions||
a.ui.ddmanager.prepareOffsets(b,c)}}})(jQuery);
(function(a,b){var c={buttons:!0,height:!0,maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0,width:!0},d={maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0},g=a.attrFn||{val:!0,css:!0,html:!0,text:!0,data:!0,width:!0,height:!0,offset:!0,click:!0};a.widget("ui.dialog",{options:{autoOpen:!0,buttons:{},closeOnEscape:!0,closeText:"close",dialogClass:"",draggable:!0,hide:null,height:"auto",maxHeight:!1,maxWidth:!1,minHeight:150,minWidth:150,modal:!1,position:{my:"center",at:"center",collision:"fit",using:function(b){var c=
a(this).css(b).offset().top;0>c&&a(this).css("top",b.top-c)}},resizable:!0,show:null,stack:!0,title:"",width:300,zIndex:1E3},_create:function(){this.originalTitle=this.element.attr("title");if("string"!==typeof this.originalTitle)this.originalTitle="";this.options.title=this.options.title||this.originalTitle;var b=this,c=b.options,d=c.title||"&#160;",g=a.ui.dialog.getTitleId(b.element),k=(b.uiDialog=a("<div></div>")).appendTo(document.body).hide().addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+
c.dialogClass).css({zIndex:c.zIndex}).attr("tabIndex",-1).css("outline",0).keydown(function(d){c.closeOnEscape&&!d.isDefaultPrevented()&&d.keyCode&&d.keyCode===a.ui.keyCode.ESCAPE&&(b.close(d),d.preventDefault())}).attr({role:"dialog","aria-labelledby":g}).mousedown(function(a){b.moveToTop(!1,a)});b.element.show().removeAttr("title").addClass("ui-dialog-content ui-widget-content").appendTo(k);var i=(b.uiDialogTitlebar=a("<div></div>")).addClass("ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix").prependTo(k),
l=a('<a href="#"></a>').addClass("ui-dialog-titlebar-close ui-corner-all").attr("role","button").hover(function(){l.addClass("ui-state-hover")},function(){l.removeClass("ui-state-hover")}).focus(function(){l.addClass("ui-state-focus")}).blur(function(){l.removeClass("ui-state-focus")}).click(function(a){b.close(a);return!1}).appendTo(i);(b.uiDialogTitlebarCloseText=a("<span></span>")).addClass("ui-icon ui-icon-closethick").text(c.closeText).appendTo(l);a("<span></span>").addClass("ui-dialog-title").attr("id",
g).html(d).prependTo(i);if(a.isFunction(c.beforeclose)&&!a.isFunction(c.beforeClose))c.beforeClose=c.beforeclose;i.find("*").add(i).disableSelection();c.draggable&&a.fn.draggable&&b._makeDraggable();c.resizable&&a.fn.resizable&&b._makeResizable();b._createButtons(c.buttons);b._isOpen=!1;a.fn.bgiframe&&k.bgiframe()},_init:function(){this.options.autoOpen&&this.open()},destroy:function(){this.overlay&&this.overlay.destroy();this.uiDialog.hide();this.element.unbind(".dialog").removeData("dialog").removeClass("ui-dialog-content ui-widget-content").hide().appendTo("body");
this.uiDialog.remove();this.originalTitle&&this.element.attr("title",this.originalTitle);return this},widget:function(){return this.uiDialog},close:function(b){var c=this,d,g;if(!1!==c._trigger("beforeClose",b)){c.overlay&&c.overlay.destroy();c.uiDialog.unbind("keypress.ui-dialog");c._isOpen=!1;c.options.hide?c.uiDialog.hide(c.options.hide,function(){c._trigger("close",b)}):(c.uiDialog.hide(),c._trigger("close",b));a.ui.dialog.overlay.resize();if(c.options.modal)d=0,a(".ui-dialog").each(function(){this!==
c.uiDialog[0]&&(g=a(this).css("z-index"),isNaN(g)||(d=Math.max(d,g)))}),a.ui.dialog.maxZ=d;return c}},isOpen:function(){return this._isOpen},moveToTop:function(b,c){var d=this.options;if(d.modal&&!b||!d.stack&&!d.modal)return this._trigger("focus",c);if(d.zIndex>a.ui.dialog.maxZ)a.ui.dialog.maxZ=d.zIndex;if(this.overlay)a.ui.dialog.maxZ+=1,this.overlay.$el.css("z-index",a.ui.dialog.overlay.maxZ=a.ui.dialog.maxZ);d={scrollTop:this.element.scrollTop(),scrollLeft:this.element.scrollLeft()};a.ui.dialog.maxZ+=
1;this.uiDialog.css("z-index",a.ui.dialog.maxZ);this.element.attr(d);this._trigger("focus",c);return this},open:function(){if(!this._isOpen){var b=this.options,c=this.uiDialog;this.overlay=b.modal?new a.ui.dialog.overlay(this):null;this._size();this._position(b.position);c.show(b.show);this.moveToTop(!0);b.modal&&c.bind("keypress.ui-dialog",function(b){if(b.keyCode===a.ui.keyCode.TAB){var c=a(":tabbable",this),e=c.filter(":first"),c=c.filter(":last");if(b.target===c[0]&&!b.shiftKey)return e.focus(1),
!1;if(b.target===e[0]&&b.shiftKey)return c.focus(1),!1}});a(this.element.find(":tabbable").get().concat(c.find(".ui-dialog-buttonpane :tabbable").get().concat(c.get()))).eq(0).focus();this._isOpen=!0;this._trigger("open");return this}},_createButtons:function(b){var c=this,d=!1,j=a("<div></div>").addClass("ui-dialog-buttonpane ui-widget-content ui-helper-clearfix"),k=a("<div></div>").addClass("ui-dialog-buttonset").appendTo(j);c.uiDialog.find(".ui-dialog-buttonpane").remove();"object"===typeof b&&
null!==b&&a.each(b,function(){return!(d=!0)});d&&(a.each(b,function(b,e){var e=a.isFunction(e)?{click:e,text:b}:e,d=a('<button type="button"></button>').click(function(){e.click.apply(c.element[0],arguments)}).appendTo(k);a.each(e,function(a,b){if("click"!==a)if(a in g)d[a](b);else d.attr(a,b)});a.fn.button&&d.button()}),j.appendTo(c.uiDialog))},_makeDraggable:function(){function b(a){return{position:a.position,offset:a.offset}}var c=this,d=c.options,g=a(document),k;c.uiDialog.draggable({cancel:".ui-dialog-content, .ui-dialog-titlebar-close",
handle:".ui-dialog-titlebar",containment:"document",start:function(g,j){k="auto"===d.height?"auto":a(this).height();a(this).height(a(this).height()).addClass("ui-dialog-dragging");c._trigger("dragStart",g,b(j))},drag:function(a,d){c._trigger("drag",a,b(d))},stop:function(i,l){d.position=[l.position.left-g.scrollLeft(),l.position.top-g.scrollTop()];a(this).removeClass("ui-dialog-dragging").height(k);c._trigger("dragStop",i,b(l));a.ui.dialog.overlay.resize()}})},_makeResizable:function(c){function d(a){return{originalPosition:a.originalPosition,
originalSize:a.originalSize,position:a.position,size:a.size}}var c=c===b?this.options.resizable:c,g=this,j=g.options,k=g.uiDialog.css("position"),c="string"===typeof c?c:"n,e,s,w,se,sw,ne,nw";g.uiDialog.resizable({cancel:".ui-dialog-content",containment:"document",alsoResize:g.element,maxWidth:j.maxWidth,maxHeight:j.maxHeight,minWidth:j.minWidth,minHeight:g._minHeight(),handles:c,start:function(b,c){a(this).addClass("ui-dialog-resizing");g._trigger("resizeStart",b,d(c))},resize:function(a,b){g._trigger("resize",
a,d(b))},stop:function(b,c){a(this).removeClass("ui-dialog-resizing");j.height=a(this).height();j.width=a(this).width();g._trigger("resizeStop",b,d(c));a.ui.dialog.overlay.resize()}}).css("position",k).find(".ui-resizable-se").addClass("ui-icon ui-icon-grip-diagonal-se")},_minHeight:function(){var a=this.options;return"auto"===a.height?a.minHeight:Math.min(a.minHeight,a.height)},_position:function(b){var c=[],d=[0,0],g;if(b){if("string"===typeof b||"object"===typeof b&&"0"in b)c=b.split?b.split(" "):
[b[0],b[1]],1===c.length&&(c[1]=c[0]),a.each(["left","top"],function(a,b){+c[a]===c[a]&&(d[a]=c[a],c[a]=b)}),b={my:c.join(" "),at:c.join(" "),offset:d.join(" ")};b=a.extend({},a.ui.dialog.prototype.options.position,b)}else b=a.ui.dialog.prototype.options.position;(g=this.uiDialog.is(":visible"))||this.uiDialog.show();this.uiDialog.css({top:0,left:0}).position(a.extend({of:window},b));g||this.uiDialog.hide()},_setOptions:function(b){var f=this,g={},j=!1;a.each(b,function(a,b){f._setOption(a,b);a in
c&&(j=!0);a in d&&(g[a]=b)});j&&this._size();this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option",g)},_setOption:function(b,c){var d=this.uiDialog;switch(b){case "beforeclose":b="beforeClose";break;case "buttons":this._createButtons(c);break;case "closeText":this.uiDialogTitlebarCloseText.text(""+c);break;case "dialogClass":d.removeClass(this.options.dialogClass).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+c);break;case "disabled":c?d.addClass("ui-dialog-disabled"):
d.removeClass("ui-dialog-disabled");break;case "draggable":var g=d.is(":data(draggable)");g&&!c&&d.draggable("destroy");!g&&c&&this._makeDraggable();break;case "position":this._position(c);break;case "resizable":(g=d.is(":data(resizable)"))&&!c&&d.resizable("destroy");g&&"string"===typeof c&&d.resizable("option","handles",c);!g&&!1!==c&&this._makeResizable(c);break;case "title":a(".ui-dialog-title",this.uiDialogTitlebar).html(""+(c||"&#160;"))}a.Widget.prototype._setOption.apply(this,arguments)},
_size:function(){var b=this.options,c,d,g=this.uiDialog.is(":visible");this.element.show().css({width:"auto",minHeight:0,height:0});if(b.minWidth>b.width)b.width=b.minWidth;c=this.uiDialog.css({height:"auto",width:b.width}).height();d=Math.max(0,b.minHeight-c);"auto"===b.height?a.support.minHeight?this.element.css({minHeight:d,height:"auto"}):(this.uiDialog.show(),b=this.element.css("height","auto").height(),g||this.uiDialog.hide(),this.element.height(Math.max(b,d))):this.element.height(Math.max(b.height-
c,0));this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option","minHeight",this._minHeight())}});a.extend(a.ui.dialog,{version:"1.8.16",uuid:0,maxZ:0,getTitleId:function(a){a=a.attr("id");a||(a=this.uuid+=1);return"ui-dialog-title-"+a},overlay:function(b){this.$el=a.ui.dialog.overlay.create(b)}});a.extend(a.ui.dialog.overlay,{instances:[],oldInstances:[],maxZ:0,events:a.map("focus,mousedown,mouseup,keydown,keypress,click".split(","),function(a){return a+".dialog-overlay"}).join(" "),
create:function(b){0===this.instances.length&&(setTimeout(function(){a.ui.dialog.overlay.instances.length&&a(document).bind(a.ui.dialog.overlay.events,function(b){if(a(b.target).zIndex()<a.ui.dialog.overlay.maxZ)return!1})},1),a(document).bind("keydown.dialog-overlay",function(c){b.options.closeOnEscape&&!c.isDefaultPrevented()&&c.keyCode&&c.keyCode===a.ui.keyCode.ESCAPE&&(b.close(c),c.preventDefault())}),a(window).bind("resize.dialog-overlay",a.ui.dialog.overlay.resize));var c=(this.oldInstances.pop()||
a("<div></div>").addClass("ui-widget-overlay")).appendTo(document.body).css({width:this.width(),height:this.height()});a.fn.bgiframe&&c.bgiframe();this.instances.push(c);return c},destroy:function(b){var c=a.inArray(b,this.instances);-1!=c&&this.oldInstances.push(this.instances.splice(c,1)[0]);0===this.instances.length&&a([document,window]).unbind(".dialog-overlay");b.remove();var d=0;a.each(this.instances,function(){d=Math.max(d,this.css("z-index"))});this.maxZ=d},height:function(){var b,c;return a.browser.msie&&
7>a.browser.version?(b=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight),c=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight),b<c?a(window).height()+"px":b+"px"):a(document).height()+"px"},width:function(){var b,c;return a.browser.msie?(b=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth),c=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth),b<c?a(window).width()+"px":b+"px"):a(document).width()+"px"},resize:function(){var b=
a([]);a.each(a.ui.dialog.overlay.instances,function(){b=b.add(this)});b.css({width:0,height:0}).css({width:a.ui.dialog.overlay.width(),height:a.ui.dialog.overlay.height()})}});a.extend(a.ui.dialog.overlay.prototype,{destroy:function(){a.ui.dialog.overlay.destroy(this.$el)}})})(jQuery);
