/*
 * jQuery Address Plugin v1.5
 * http://www.asual.com/jquery/address/
 *
 * Copyright (c) 2009-2010 Rostislav Hristov
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 */
(function(c){c.address=function(){var n=function(a){c(c.address).trigger(c.extend(c.Event(a),function(){for(var a={},d=c.address.parameterNames(),e=0,f=d.length;e<f;e++)a[d[e]]=c.address.parameter(d[e]);return{value:c.address.value(),path:c.address.path(),pathNames:c.address.pathNames(),parameterNames:d,parameters:a,queryString:c.address.queryString()}}.call(c.address)))},p=function(a){return Array.prototype.slice.call(a)},h=function(a,b,d){c().bind.apply(c(c.address),Array.prototype.slice.call(arguments));
return c.address},B=function(){return u.pushState&&d.state!==k},N=function(){return("/"+i.pathname.replace(RegExp(d.state),"")+i.search+(C()?"#"+C():"")).replace(M,"/")},C=function(){var a=i.href.indexOf("#");return-1!=a?s(i.href.substr(a+1),j):""},q=function(){return B()?N():C()},I=function(a){a=a.toString();return(d.strict&&"/"!=a.substr(0,1)?"/":"")+a},s=function(a,b){return d.crawlable&&b?(""!==a?"!":"")+a:a.replace(/^\!/,"")},r=function(a,b){return parseInt(a.css(b),10)},y=function(){if(!D){var a=
q();e!=a&&(v&&7>w?i.reload():(v&&!E&&d.history&&o(J,50),e=a,x(j)))}},x=function(a){n(O);n(a?P:Q);o(Y,10)},Y=function(){if("null"!==d.tracker&&null!==d.tracker){var a=c.isFunction(d.tracker)?d.tracker:f[d.tracker],b=(i.pathname+i.search+(c.address&&!B()?c.address.value():"")).replace(/\/\//,"/").replace(/^\/$/,"");c.isFunction(a)?a(b):c.isFunction(f.urchinTracker)?f.urchinTracker(b):f.pageTracker!==k&&c.isFunction(f.pageTracker._trackPageview)?f.pageTracker._trackPageview(b):f._gaq!==k&&c.isFunction(f._gaq.push)&&
f._gaq.push(["_trackPageview",decodeURI(b)])}},J=function(){var a="javascript:"+j+";document.open();document.writeln('<html><head><title>"+l.title.replace(/\'/g,"\\'")+"</title><script>var "+t+' = "'+q()+(l.domain!=i.hostname?'";document.domain="'+l.domain:"")+"\";<\/script></head></html>');document.close();";7>w?g.src=a:g.contentWindow.location.replace(a)},S=function(){if(z&&-1!=R){var a,b,c=z.substr(R+1).split("&");for(a=0;a<c.length;a++)b=c[a].split("="),/^(autoUpdate|crawlable|history|strict|wrap)$/.test(b[0])&&
(d[b[0]]=isNaN(b[1])?/^(true|yes)$/i.test(b[1]):0!==parseInt(b[1],10)),/^(state|tracker)$/.test(b[0])&&(d[b[0]]=b[1]);z=null}e=q()},U=function(){if(!T){T=m;S();var a=function(){Z.call(this);$.call(this)},b=c("body").ajaxComplete(a);a();d.wrap&&(c("body > *").wrapAll('<div style="padding:'+(r(b,"marginTop")+r(b,"paddingTop"))+"px "+(r(b,"marginRight")+r(b,"paddingRight"))+"px "+(r(b,"marginBottom")+r(b,"paddingBottom"))+"px "+(r(b,"marginLeft")+r(b,"paddingLeft"))+'px;" />').parent().wrap('<div id="'+
t+'" style="height:100%;overflow:auto;position:relative;'+(F&&!window.statusbar.visible?"resize:both;":"")+'" />'),c("html, body").css({height:"100%",margin:0,padding:0,overflow:"hidden"}),F&&c('<style type="text/css" />').appendTo("head").text("#"+t+"::-webkit-resizer { background-color: #fff; }"));if(v&&!E)a=l.getElementsByTagName("frameset")[0],g=l.createElement((a?"":"i")+"frame"),g.src="javascript:"+j,a?(a.insertAdjacentElement("beforeEnd",g),a[a.cols?"cols":"rows"]+=",0",g.noResize=m,g.frameBorder=
g.frameSpacing=0):(g.style.display="none",g.style.width=g.style.height=0,g.tabIndex=-1,l.body.insertAdjacentElement("afterBegin",g)),o(function(){c(g).bind("load",function(){var a=g.contentWindow;e=a[t]!==k?a[t]:"";if(e!=q())x(j),i.hash=s(e,m)});g.contentWindow[t]===k&&J()},50);o(function(){n("init");x(j)},1);B()||(E?f.addEventListener?f.addEventListener(A,y,j):f.attachEvent&&f.attachEvent("on"+A,y):aa(y,50))}},Z=function(){var a,b=c("a"),d=b.size(),e=-1,f=function(){++e!=d&&(a=c(b.get(e)),a.is('[rel*="address:"]')&&
a.address('[rel*="address:"]'),o(f,1))};o(f,1)},$=function(){if(d.crawlable){var a=i.pathname.replace(/\/$/,"");-1!=c("body").html().indexOf("_escaped_fragment_")&&c('a[href]:not([href^=http]), a[href*="'+document.domain+'"]').each(function(){var b=c(this).attr("href").replace(/^http:/,"").replace(RegExp(a+"/?$"),"");(""===b||-1!=b.indexOf("_escaped_fragment_"))&&c(this).attr("href","#"+encodeURI(decodeURIComponent(b.replace(/\/(.*)\?_escaped_fragment_=(.*)$/)),"!$2"))})}},k,t="jQueryAddress",A="hashchange",
O="change",P="internalChange",Q="externalChange",m=!0,j=!1,d={autoUpdate:m,crawlable:j,history:m,strict:m,wrap:j},G=c.browser,w=parseFloat(G.version),v=!c.support.opacity,F=G.webkit||G.safari,f;try{f=top.document!==k?top:window}catch(ca){f=window}var l=f.document,u=f.history,i=f.location,aa=setInterval,o=setTimeout,M=/\/{2,9}/g,V=navigator.userAgent,E="on"+A in f,g,z=c("script:last").attr("src"),R=z?z.indexOf("?"):-1,K=l.title,D=j,T=j,L=m,W=m,H=j,e=q();if(v){w=parseFloat(V.substr(V.indexOf("MSIE")+
4));l.documentMode&&l.documentMode!=w&&(w=8!=l.documentMode?7:8);var X=l.onpropertychange;l.onpropertychange=function(){X&&X.call(l);if(l.title!=K&&-1!=l.title.indexOf("#"+q()))l.title=K}}if(u.navigationMode)u.navigationMode="compatible";if("complete"==document.readyState)var ba=setInterval(function(){c.address&&(U(),clearInterval(ba))},50);else S(),c(U);c(window).bind("popstate",function(){e!=q()&&(e=q(),x(j))}).bind("unload",function(){f.removeEventListener?f.removeEventListener(A,y,j):f.detachEvent&&
f.detachEvent("on"+A,y)});return{bind:function(a,b,c){return h.apply(this,p(arguments))},init:function(a,b){return h.apply(this,["init"].concat(p(arguments)))},change:function(a,b){return h.apply(this,[O].concat(p(arguments)))},internalChange:function(a,b){return h.apply(this,[P].concat(p(arguments)))},externalChange:function(a,b){return h.apply(this,[Q].concat(p(arguments)))},baseURL:function(){var a=i.href;-1!=a.indexOf("#")&&(a=a.substr(0,a.indexOf("#")));/\/$/.test(a)&&(a=a.substr(0,a.length-
1));return a},autoUpdate:function(a){return a!==k?(d.autoUpdate=a,this):d.autoUpdate},crawlable:function(a){return a!==k?(d.crawlable=a,this):d.crawlable},history:function(a){return a!==k?(d.history=a,this):d.history},state:function(a){if(a!==k){d.state=a;var b=N();d.state!==k&&(u.pushState?"/#/"==b.substr(0,3)&&i.replace(d.state.replace(/^\/$/,"")+b.substr(2)):"/"!=b&&b.replace(/^\/#/,"")!=C()&&o(function(){i.replace(d.state.replace(/^\/$/,"")+"/#"+b)},1));return this}return d.state},strict:function(a){return a!==
k?(d.strict=a,this):d.strict},tracker:function(a){return a!==k?(d.tracker=a,this):d.tracker},wrap:function(a){return a!==k?(d.wrap=a,this):d.wrap},update:function(){H=m;this.value(e);H=j;return this},title:function(a){return a!==k?(o(function(){K=l.title=a;if(W&&g&&g.contentWindow&&g.contentWindow.document)g.contentWindow.document.title=a,W=j;!L&&G.mozilla&&i.replace(-1!=i.href.indexOf("#")?i.href:i.href+"#");L=j},50),this):l.title},value:function(a){if(a!==k){a=I(a);"/"==a&&(a="");if(e==a&&!H)return;
L=m;e=a;if(d.autoUpdate||H)if(x(m),B())u[d.history?"pushState":"replaceState"]({},"",d.state.replace(/\/$/,"")+(""===e?"/":e));else{D=m;if(F)d.history?i.hash="#"+s(e,m):i.replace("#"+s(e,m));else if(e!=q())d.history?i.hash="#"+s(e,m):i.replace("#"+s(e,m));v&&!E&&d.history&&o(J,50);F?o(function(){D=j},1):D=j}return this}return I(e)},path:function(a){if(a!==k){var b=this.queryString(),c=this.hash();this.value(a+(b?"?"+b:"")+(c?"#"+c:""));return this}return I(e).split("#")[0].split("?")[0]},pathNames:function(){var a=
this.path(),b=a.replace(M,"/").split("/");("/"==a.substr(0,1)||0===a.length)&&b.splice(0,1);"/"==a.substr(a.length-1,1)&&b.splice(b.length-1,1);return b},queryString:function(a){if(a!==k){var b=this.hash();this.value(this.path()+(a?"?"+a:"")+(b?"#"+b:""));return this}a=e.split("?");return a.slice(1,a.length).join("?").split("#")[0]},parameter:function(a,b,d){var e,f;if(b!==k){var h=this.parameterNames();f=[];b=b?b.toString():"";for(e=0;e<h.length;e++){var i=h[e],g=this.parameter(i);"string"==typeof g&&
(g=[g]);i==a&&(g=null===b||""===b?[]:d?g.concat([b]):[b]);for(var j=0;j<g.length;j++)f.push(i+"="+g[j])}-1==c.inArray(a,h)&&null!==b&&""!==b&&f.push(a+"="+b);this.queryString(f.join("&"));return this}if(b=this.queryString()){d=[];f=b.split("&");for(e=0;e<f.length;e++)b=f[e].split("="),b[0]==a&&d.push(b.slice(1).join("="));if(0!==d.length)return 1!=d.length?d:d[0]}},parameterNames:function(){var a=this.queryString(),b=[];if(a&&-1!=a.indexOf("="))for(var a=a.split("&"),d=0;d<a.length;d++){var e=a[d].split("=")[0];
-1==c.inArray(e,b)&&b.push(e)}return b},hash:function(a){if(a!==k)return this.value(e.split("#")[0]+(a?"#"+a:"")),this;a=e.split("#");return a.slice(1,a.length).join("#")}}}();c.fn.address=function(n){var p;"string"==typeof n&&(p=n,n=void 0);c(this).attr("address")||c(p?p:this).live("click",function(h){if(h.shiftKey||h.ctrlKey||h.metaKey||2==h.which)return!0;c(this).is("a")&&(h.preventDefault(),h=n?n.call(this):/address:/.test(c(this).attr("rel"))?c(this).attr("rel").split("address:")[1].split(" ")[0]:
void 0!==c.address.state()&&!/^\/?$/.test(c.address.state())?c(this).attr("href").replace(RegExp("^(.*"+c.address.state()+"|\\.)"),""):c(this).attr("href").replace(/^(#\!?|\.)/,""),c.address.value(h))}).live("submit",function(h){c(this).is("form")&&(h.preventDefault(),h=c(this).attr("action"),h=n?n.call(this):(-1!=h.indexOf("?")?h.replace(/&$/,""):h+"?")+c(this).serialize(),c.address.value(h))}).attr("address",!0);return this}})(jQuery);
